/**
 * Generate TypeScript types for USWDS icon names
 *
 * Reads all SVG filenames from @uswds/uswds/dist/img/usa-icons/ and generates
 * a TypeScript file with type definitions for autocomplete support.
 *
 * Run: pnpm generate:icon-types
 */

import { readdirSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const USWDS_ICONS_PATH = resolve(
  __dirname,
  '../node_modules/@uswds/uswds/dist/img/usa-icons'
);
const OUTPUT_PATH = resolve(__dirname, '../src/components/icons/uswds/types.ts');

function generateIconTypes(): void {
  if (!existsSync(USWDS_ICONS_PATH)) {
    console.error(`Error: USWDS icons not found at ${USWDS_ICONS_PATH}`);
    console.error('Run: pnpm add @uswds/uswds');
    process.exit(1);
  }

  const files = readdirSync(USWDS_ICONS_PATH);
  const iconNames = files
    .filter((file) => file.endsWith('.svg'))
    .map((file) => file.replace('.svg', ''))
    .sort();

  if (iconNames.length === 0) {
    console.error('Error: No SVG icons found');
    process.exit(1);
  }

  const typeUnion = iconNames.map((name) => `  | '${name}'`).join('\n');

  const content = `/**
 * USWDS Icon Names
 *
 * Auto-generated by scripts/generate-icon-types.ts
 * Do not edit manually - run: pnpm generate:icon-types
 *
 * Total icons: ${iconNames.length}
 */

export type IconName =
${typeUnion};

/**
 * Array of all available icon names for runtime validation
 */
export const ICON_NAMES: IconName[] = [
${iconNames.map((name) => `  '${name}',`).join('\n')}
] as const;

/**
 * Check if a string is a valid icon name
 */
export function isValidIconName(name: string): name is IconName {
  return ICON_NAMES.includes(name as IconName);
}
`;

  writeFileSync(OUTPUT_PATH, content);
  console.log(`Generated ${OUTPUT_PATH}`);
  console.log(`Total icons: ${iconNames.length}`);
}

generateIconTypes();
