#!/bin/bash
set -e

echo "=== Worktree Initialization ==="

# Get worktree information
WORKTREE_PATH=$(pwd)
WORKTREE_NAME=$(basename "$WORKTREE_PATH")
BRANCH_NAME=$(git branch --show-current 2>/dev/null || echo "main")

echo "Worktree: $WORKTREE_NAME"
echo "Branch: $BRANCH_NAME"
echo ""

# Generate unique port offsets based on hash of worktree path
HASH=$(echo -n "$WORKTREE_PATH" | md5 2>/dev/null | cut -c1-4 || echo -n "$WORKTREE_PATH" | md5sum | cut -c1-4)
PORT_OFFSET=$((0x$HASH % 1000))

API_PORT=$((3000 + PORT_OFFSET))
WEB_PORT=$((5173 + PORT_OFFSET))

# Generate database name from branch (sanitized)
DB_NAME="ship_${BRANCH_NAME//[^a-zA-Z0-9]/_}"

echo "Generating configuration..."
echo "  API Port: $API_PORT"
echo "  Web Port: $WEB_PORT"
echo "  Database: $DB_NAME"
echo ""

# Create API .env.local
cat > api/.env.local << EOF
# Auto-generated by worktree-init.sh on $(date)
# Worktree: $WORKTREE_NAME
# Branch: $BRANCH_NAME

PORT=$API_PORT
NODE_ENV=development
DATABASE_URL=postgresql://localhost:5432/$DB_NAME
LOG_LEVEL=debug
CORS_ORIGIN=http://localhost:$WEB_PORT
EOF

# Create Web .env.local
cat > web/.env.local << EOF
# Auto-generated by worktree-init.sh on $(date)
# Worktree: $WORKTREE_NAME
# Branch: $BRANCH_NAME

VITE_API_URL=http://localhost:$API_PORT
VITE_PORT=$WEB_PORT
EOF

echo "Configuration files created:"
echo "  - api/.env.local"
echo "  - web/.env.local"
echo ""

# Install dependencies if node_modules missing
if [ ! -d "node_modules" ]; then
  echo "Installing dependencies..."
  pnpm install
  echo ""
fi

# Build shared package if dist missing
if [ ! -d "shared/dist" ]; then
  echo "Building shared package..."
  pnpm build:shared
  echo ""
fi

# Create database if it doesn't exist
if ! psql -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
  echo "Creating database $DB_NAME..."
  createdb "$DB_NAME" 2>/dev/null || echo "  Note: Could not create database automatically"
  echo ""
fi

# Seed database (idempotent - safe to run multiple times)
echo "Seeding database..."
pnpm db:seed
echo ""

echo "=== Initialization Complete ==="
echo ""
echo "Your servers will run on:"
echo "  API: http://localhost:$API_PORT"
echo "  Web: http://localhost:$WEB_PORT"
echo ""
echo "Run 'pnpm dev' to start development servers."
